NDefines.NMilitary.BASE_DIVISION_BRIGADE_GROUP_COST = 0;
NDefines.NMilitary.BASE_DIVISION_BRIGADE_CHANGE_COST = 0;
NDefines.NMilitary.BASE_DIVISION_SUPPORT_SLOT_COST = 0;
NDefines.NMilitary.MAX_ARMY_EXPERIENCE = 1000;
NDefines.NMilitary.MAX_NAVY_EXPERIENCE = 1000;
NDefines.NMilitary.MAX_AIR_EXPERIENCE = 1000;
NDefines.NMilitary.DEPLOY_TRAINING_MAX_LEVEL = 2;
NDefines.NMilitary.PROMOTE_LEADER_CP_COST = 0.0;	

NDefines.NCountry.POPULATION_YEARLY_GROWTH_BASE = 0.0;
NDefines.NCountry.BASE_FUEL_CAPACITY = 100000;
NDefines.NCountry.SPECIAL_FORCES_CAP_MIN = 200;


NDefines.NCharacter.SPECIALIST_ADVISOR_MIN_RANK = 2;
NDefines.NCharacter.EXPERT_ADVISOR_MIN_RANK = 4;
NDefines.NCharacter.GENIUS_ADVISOR_MIN_RANK = 6;

NDefines.NDiplomacy.VOLUNTEERS_PER_COUNTRY_ARMY = 0;
NDefines.NDiplomacy.VOLUNTEERS_PER_TARGET_PROVINCE = 0;
NDefines.NDiplomacy.VOLUNTEERS_DIVISIONS_REQUIRED = 1;
NDefines.NDiplomacy.OPINION_PER_VOLUNTEER = 10;
NDefines.NDiplomacy.MAX_OPINION_FROM_VOLUNTEERS = 50;

NDefines.NGame.LAG_DAYS_FOR_LOWER_SPEED = 100;			
NDefines.NGame.LAG_DAYS_FOR_PAUSE = 250;
NDefines.NGame.GAME_SPEED_SECONDS = { 600.0, 0.5, 0.2, 0.1, 0.0 };

NDefines.NGame.DIPLOMACY_ACCEPT_ATTACHE_BASE = 200;
NDefines.NGame.DIPLOMACY_ACCEPT_ATTACHE_OPINION_TRASHHOLD = 0;

NDefines.NSupply.RAILWAY_CONVERSION_COOLDOWN = 5;

NDefines.NAir.AIR_DEPLOYMENT_DAYS = 0;
NDefines.NAir.EFFICIENCY_REGION_CHANGE_DAILY_GAIN_STRATEGIC_BOMBER = 0.036;
NDefines.NAir.EFFICIENCY_REGION_CHANGE_DAILY_GAIN_TACTICAL_BOMBER = 0.096;			


NDefines.NProduction.BASE_LICENSE_IC_COST = 0;	
NDefines.NProduction.LICENSE_IC_COST_YEAR_INCREASE = 0;	
NDefines.NProduction.MIN_POSSIBLE_TRAINING_MANPOWER = 10000000;
NDefines.NProduction.EQUIPMENT_MODULE_ADD_XP_COST = 0;				
NDefines.NProduction.EQUIPMENT_MODULE_REPLACE_XP_COST = 0;				
NDefines.NProduction.EQUIPMENT_MODULE_CONVERT_XP_COST = 0;				
NDefines.NProduction.EQUIPMENT_MODULE_REMOVE_XP_COST = 0;
NDefines.NProduction.RAILWAY_GUN_MAX_MIL_FACTORIES_PER_LINE = 10;
NDefines.NProduction.MAX_MIL_FACTORIES_PER_LINE = 300;
NDefines.NProduction.CAPITAL_SHIP_MAX_NAV_FACTORIES_PER_LINE = 200;
NDefines.NProduction.CONVOY_MAX_NAV_FACTORIES_PER_LINE = 200;
NDefines.NProduction.DEFAULT_MAX_NAV_FACTORIES_PER_LINE = 200;
